### ISSUE TITLE
For ID 19

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/draft-ietf-tls-tls13-vectors#1]
I would like to see a updated version for ID19 before the hackathon.

**Comment by martinthomson** [comment]
So would I, but that depends on NSS implementing -19 and we're a little behind.

**Comment by Lekensteyn** [comment]
Based on 26f548b52c0d1ceda0fb1d9fb036602bd0417429, isn't the branch currently up-to-date with draft -20?

**Comment by martinthomson** [comment]
That is correct, though I wanted to keep this open until the changes land in NSS trunk. I will need to change a few things when that happens.

**Comment by martinthomson** [comment]
OBE, we have -21 now.
