### ISSUE TITLE
Informational or BCP or Proposed Standard?

### ISSUE THREAD

**Issue by seanturner** [tlswg/draft-ietf-tls-tls13-vectors#5]
I don't really have a strong opinion on this, but I am sure somebody will.  Many of the "example" RFCs are Informational but some are BCP (based on the following):
https://datatracker.ietf.org/doc/search?name=examples&sort=&rfcs=on&activedrafts=on&by=group&group=

**Comment by martinthomson** [comment]
BCP makes no sense to me. I think that informational is fine.
